
FROM node:18 AS frontend-build
WORKDIR /kirin-front

COPY kirin-front/package*.json ./
RUN npm install

COPY kirin-front/ .
RUN npm run build

FROM maven:3.9.4-eclipse-temurin-17 AS backend-build
WORKDIR /kirin-api

COPY kirin-api/pom.xml .
RUN mvn dependency:resolve

COPY kirin-api/src ./src
RUN mvn clean package -DskipTests

FROM openjdk:17-jdk-slim

WORKDIR /app

COPY --from=backend-build /kirin-api/target/*.jar /app/app.jar

COPY --from=frontend-build /kirin-front/dist /app/public

WORKDIR /app

EXPOSE 8080

CMD ["java", "-jar", "app.jar"]
